version: '3.8'
services:
  push-ntfy-app:
    container_name: push_ntfy_api
    build: 
      context: .
    image: frankb/push-ntfy-app:latest
    ports:
      - "1081:1081"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /home/frankb/python-scripts/push_notification/notification.db:/app/notification.db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro